apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: margaiwangara/eventwise-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './**/*.py'
            dest: .
